name: Code Quarkus CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - 'build_deploy.sh'
      - 'Makefile'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/stale.yml'
      - '.dependabot/**'
      - 'openshift/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened, ready_for_review, edited]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
      - 'build_deploy.sh'
      - 'Makefile'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/stale.yml'
      - '.dependabot/**'
      - 'openshift/**'

env:
  # Workaround testsuite locale issue
  LANG: en_US.UTF-8

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    # Skip draft PRs and those with WIP in the subject, rerun as soon as its removed
    if: "github.event_name != 'pull_request' || ( \
           github.event.pull_request.draft == false && \
           github.event.pull_request.state != 'closed' && \
           contains(github.event.pull_request.title, 'wip ') == false && \
           contains(github.event.pull_request.title, '[wip]') == false && \
           (
             github.event.action != 'edited' || \
             contains(github.event.changes.title.from, 'wip ') || \
             contains(github.event.changes.title.from, '[wip]') \
           ) \
         )"
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 11
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          java-version: openjdk11
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Yarn Packages
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: /.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('src/main/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build
        run: |
          ./mvnw -e -B -DskipTests=true clean install
      - name: Test
        run: |
          ./mvnw -e -B test
